class PracticeData{
  static late List<String> practiceType = ['Primary Care Physician', 'Specialist Physician'];
  static late Map<String, List<String>> practiceSubtypes = {
    'Primary Care Physician': [
      'Family Physician',
      'Geriatrician',
      'Internist',
      'Pediatrician',
    ],
    'Specialist Physician': [
      'Allergist /Immunologist',
      'Anesthesiologist',
      'Cardiologist',
      'Colon and Rectal Surgeon',
      'Critical Care Medicine Specialist',
      'Dentist',
      'Dermatologist',
      'Endocrinologist',
      'Emergency Medicine Specialist',
      'Gastroenterologist',
      'Haematologist',
      'Hepatologist',
      'Hospice and Palliative Medicine Specialist',
      'Infectious Disease Specialist',
      'Medical Geneticist',
      'Neonatologist',
      'Nephrologist',
      'Neurologist',
      'Nuclear Medicine Radiologist',
      'Obstetrician and Gynecologist',
      'Oncologist',
      'Ophthalmologist',
      'Osteopath',
      'Otolaryngologist/ENT Specialist',
      'Pathologist',
      'Physiatrist',
      'Plastic Surgeon',
      'Podiatrist',
      'Preventive Medicine Specialist',
      'Psychiatrist',
      'Pulmonologist',
      'Radiologist',
      'Rheumatologist',
      'Surgeon',
      'Urologist',
    ],
  };

  static List<String> addAllSubpractices() {
    final  List<String>? all = practiceSubtypes['Primary Care Physician'];
    all!.addAll(practiceSubtypes['Specialist Physician']!);
    return all;
  }

  static List<String> allSubpractices = addAllSubpractices();

  static Map<String, String> practiceDescription = {
    'Allergist /Immunologist':
    'Specialists in allergy and immunology work with both adult and pediatric patients suffering from allergies and diseases of the respiratory tract or immune system. They may help patients suffering from common diseases such as asthma, eczema, food and drug allergies, insect sting allergies, immune deficiencies, some autoimmune diseases and diseases of the lung.',
    'Anesthesiologist':
    'These doctors give you drugs to numb your pain or to put you under during surgery, childbirth, or other procedures. They monitor your vital signs while you’re under anesthesia.',
    'Cardiologist':
    'Cardiologists are the specialists in the identification and treatment of diseases associated with the cardiovascular system (i.e. encompassing the heart and blood vessels). They also educate their patients about the causes of heart disease and determine the best treatment for their unique condition. You might see them for heart failure, a heart attack, high blood pressure, or an irregular heartbeat.',
    'Colon and Rectal Surgeon':
    'You would see these doctors for problems with your small intestine, colon, and bottom. They can treat colon cancer, hemorrhoids, and inflammatory bowel disease.',
    'Critical Care Medicine Specialist':
    'They care for people who are critically ill or injured, often heading intensive care units in hospitals. You might see them if your heart or other organs are failing or if you’ve been in an accident.',
    'Dentist':
    'A dentist, also known as a dental surgeon, is a surgeon who specializes in dentistry, the diagnosis, prevention, and treatment of diseases and conditions of the oral cavity.',
    'Dermatologist':
    'Dermatologists are physicians who treat adult and pediatric patients with disorders of the skin, hair, nails, scars, acne, or skin allergies and adjacent mucous membranes. They diagnose everything from skin cancer, tumors, inflammatory diseases of the skin, and infectious diseases. They also perform skin biopsies and dermatological surgical procedures.',
    'Endocrinologist':
    'Endocrinologists treat disorders and conditions that affect the endocrine system. This system involves various glands that make and release hormones in the body. These are experts on hormones and metabolism. They can treat conditions like diabetes, thyroid problems, infertility, and calcium and bone disorders.',
    'Emergency Medicine Specialist':
    'Physicians specializing in emergency medicine provide care for adult and pediatric patients in emergency situations. These doctors make life-or-death decisions for sick and injured people, usually in an emergency room to prevent further injury. Their job is to save lives and to avoid or lower the chances of disability.',
    'Family Physician':
    'While many medical specialties focus on a certain function of the body or particular organ, family medicine focuses on integrated care and treating the patient as a whole. They care for the whole family, including children, adults, and the elderly. They do routine checkups and screening tests, give you flu and immunization shots, and manage diabetes and other ongoing medical conditions.',
    'Gastroenterologist':
    'They’re specialists in digestive organs, including the stomach, bowels, esophagus, pancreas, liver, small intestine, colon, and gallbladder. You might see them for abdominal pain, ulcers, diarrhea, jaundice, or cancers in your digestive organs. They also perform procedures such as endoscopy, sigmoidoscopy, colonoscopy and other tests for colon cancer.',
    'Geriatrician':
    'These doctors care for the elderly. They can treat people in their homes, doctors offices, nursing homes, assisted-living centers, and hospitals.',
    'Haematologist':
    'These are specialists in diseases of the blood, spleen, and lymph glands, like sickle cell disease, anemia, hemophilia, and leukemia.',
    'Hepatologist':
    'Hepatologists are specialized doctors in the prevention, identification and treatment of diseases that affect the liver, gall bladder, biliary tree and pancreas. Hepatologists deal most frequently with viral hepatitis and diseases related to alcohol',
    'Hospice and Palliative Medicine Specialist':
    'They work with people who are nearing death. They’re experts in pain management. They work with a team of other doctors to keep up your quality of life.',
    'Infectious Disease Specialist':
    'They diagnose and treat infections in any part of your body, like fevers, Lyme disease, pneumonia, tuberculosis, and HIV and AIDS. Some of them specialize in preventive medicine or travel medicine.',
    'Internist':
    'An internist is a physician who treats diseases of the heart, blood, kidneys, joints, digestive, respiratory, and vascular systems (internal organs) of adolescent, adult, and elderly patients. These primary-care doctors treat both common and complex illnesses. You’ll likely visit them or your family doctor first for any condition. Internists often have advanced training in a host of subspecialties, like heart disease, cancer, or adolescent or sleep medicine.',
    'Medical Geneticist':
    'A medical geneticist is a physician who treats hereditary disorders and diagnoses diseases that are caused by genetic defects. Medical geneticists may provide patients with therapeutic interventions and specialized counseling. They also educate patients and their families on their diagnoses and how to cope with their genetic disorder. Medical geneticists conduct cytogenetic, radiologic, ,biochemical testing, some other screening tests and scientific research in the field.',
    'Neonatologist':
    'Neonatology is a subspecialty of pediatrics that consists of the medical care of newborn infants, especially the ill or premature newborn. It is a hospital-based specialty, and is usually practised in neonatal intensive care units. They may also provide antenatal consultation for women with certain risk factors, such as multiple births.',
    'Nephrologist':
    'They treat kidney diseases as well as high blood pressure and fluid and mineral imbalances linked to kidney disease. Nephrologists can also perform kidney transplants and dialysis.',
    'Neurologist':
    'Neurologists diagnose and treat diseases of the brain, spinal cord, peripheral nerves, muscles, autonomic nervous system, and blood vessels. Neurologists treat patients suffering from strokes, seizures, brain and spinal tumors, epilepsy, Parkinson\'s disease, and Alzheimer\'s disease.',
    'Nuclear Medicine Radiologist':
    'They use radioactive materials to diagnose and treat diseases. Utilizing techniques such as scintigraphy, these physicians analyze images of the body\'s organs to visualize certain diseases. They may also use radiopharmaceuticals to treat hyperthyroidism, thyroid cancer, tumors, and bone cancer.',
    'Obstetrician and Gynecologist':
    'Often called OB/GYNs, these doctors focus on women\'s health. Obstetrician deals with all aspects of pregnancy from delivering babies and providing medical care to women during pregnancy (antenatal care) and after the birth (postnatal care). They have the skills to manage complex or high-risk pregnancies and births, and can perform interventions and caesareans (C Sections). OB/GYNs are trained in both areas. But some of them may focus on women\'s reproductive health (gynecologists) and provide therapies to help you get pregnant, such as fertility treatments',
    'Oncologist':
    'These internists are cancer specialists. They do chemotherapy treatments and often work with radiation oncology and surgical oncology. A Radiation oncologists treat cancer with the use of high-energy radiation by targeting them in small areas of the body. They damage the DNA of cancer cells, preventing further growth. A Surgical oncologist is a surgeon who specializes in performing biopsies and removing cancerous tumors and surrounding tissue, as well as other cancer-related operations',
    'Ophthalmologist':
    'Physicians specializing in ophthalmology develop comprehensive medical and surgical care of the eyes. You can call them eye doctors. Ophthalmologists diagnose and treat vision problems. They may treat strabismus, diabetic retinopathy, or perform surgeries on cataracts or corneal transplantation.They can prescribe glasses or contact lenses and diagnose and treat diseases like glaucoma. Unlike optometrists, they’re medical doctors who can treat every kind of eye condition as well as operate on the eyes.',
    'Osteopath':
    'Doctors of osteopathic medicine (DO) are fully licensed medical doctors just like MDs. Their training stresses a “whole body” approach. Osteopaths use the latest medical technology but also the body’s natural ability to heal itself.',
    'Otolaryngologist/ENT Specialist':
    'Otolaryngologists are sometimes known as “ear, nose, and throat” (ENT) doctors. They treat diseases in the ears, nose, throat, tonsils, sinuses, head, neck, and respiratory system. They also can do reconstructive and plastic surgery on your head and neck.',
    'Pathologist':
    'A physician specializing in pathology studies the causes and nature of diseases. Through microscopic examination and clinical lab tests, pathologists work to diagnose, monitor, and treat diseases.They examine tissues, cells, and body fluids, applying biological, chemical, and physical sciences within the laboratory. They may examine tissues to determine whether an organ transplant is needed, or they may examine the blood of a pregnant woman to ensure the health of the fetus.',
    'Pediatrician':
    'They care for children from infancy (birth) to adolescence. Pediatricians practice preventative medicine and also diagnose common childhood diseases, such as asthma, allergies, and croup.Some pediatricians specialize in pre-teens and teens, child abuse, or children\'s developmental issues.',
    'Physiatrist':
    'These are Physicians specializing in physical medicine and rehabilitation work to help patients with disabilities of the brain, spinal cord, nerves, bones, joints, ligaments, muscles, tendons, sports injuries as well as other disabilities caused by accidents or diseases. Physiatrist work with patients of all ages and design care plans for conditions, such as spinal cord or brain injury, stroke, multiple sclerosis, and musculoskeletal and pediatric rehabilitation. Unlike many other medical specialties, physiatrists work to improve patient quality of life, rather than seek medical cures.',
    'Plastic Surgeon':
    'You might call them cosmetic surgeons. They rebuild or repair your skin, face, hands, breasts, or body. That can happen after an injury or disease or for cosmetic reasons.',
    'Podiatrist':
    'They care for problems in your ankles and feet. That can include injuries from accidents or sports or from ongoing health conditions like diabetes. Some podiatrists have advanced training in other subspecialties of the foot.',
    'Preventive Medicine Specialist':
    'They focus on keeping you well. They may work in public health or at hospitals. Some focus on treating people with addictions, illnesses from exposure to drugs, chemicals, and poisons, and other areas.  Their expertise goes far beyond preventative practices in clinical medicine, covering elements of biostatistics, epidemiology, environmental and occupational medicine, and even the evaluation and management of health services and healthcare organizations. The field combines interdisciplinary elements of medical, social, economic, and behavioral sciences to understand the causes of disease and injury in population groups.',
    'Psychiatrist':
    'These doctors work with people with mental, emotional, or addictive disorders. They can diagnose and treat depression, schizophrenia, substance abuse, anxiety disorders, and sexual and gender identity issues. Understanding the connections between genetics, emotion, and mental illness, is important while psychiatrists also conduct medical laboratory and psychological tests to diagnose and treat patients.',
    'Pulmonologist':
    'Pulmonologists focus on the organs involved with breathing. These include the lungs and heart. You would see these specialists for problems like lung cancer, pneumonia, asthma, emphysema, and trouble sleeping caused by breathing difficulty and other breathing issues. Pulmonologists may work in hospitals to provide ventilation or life support',
    'Radiologist':
    'A radiologist specializes in diagnosing and treating conditions using medical imaging tests. They use X-rays, ultrasound, and other imaging tests to diagnose diseases. They may read and interpret scans such as X-rays, MRIs, mammograms, ultrasound, and CT scans.They may be one of three types: 1)Diagnostic radiologists: They use imaging procedures to look for health problems. 2)Interventional radiologists: They use imaging, including X-rays and MRI scans, paired with medical procedures to treat conditions such as heart disease, stroke, and cancer. 3)Radiation oncologists: They prescribe cancer treatment using radiation therapy.',
    'Rheumatologist':
    'They specialize in arthritis and other diseases in your joints, muscles, bones, and tendons. You might see them for your osteoporosis (weak bones), back pain, gout, tendinitis from sports or repetitive injuries, and fibromyalgia.',
    'Surgeon':
    'These doctors can operate on all parts of your body. They can take out tumors, appendices, or gallbladders and repair hernias. Many surgeons have subspecialties, like cancer, hand, or vascular surgery.',
    'Urologist':
    'Urologists treat conditions of the urinary tract in both males and females, for example like a leaky bladder. They also focus on male reproductive health and treat male infertility and do prostate exams.',
  };

  static Map<String, List<String>> practiceDiagnosis = {
    'Allergist /Immunologist': [
      'asthma',
      'eczema',
      'food allergies',
      'drug allergies',
      'insect sting allergies',
      'immune deficiencies',
      'autoimmune diseases',
      'diseases of the lung',
      'diseases of the respiratory tract',
      'diseases of the immune system',
      'multiple sclerosis',
      'myasthenia gravis',
      'coeliac Disease',
      'inflammatory bowel disease',
      'aplastic anemia',
      'pernicious anemia',
      'reactive arthritis',
      'rheumatoid arthritis',
      'guillain-barré syndrome',
      'sjögren syndrome',
      'systemic lupus erythematosus',
      'type 1 diabetes',
    ],
    'Anesthesiologist': [
      'administering pain relief',
      'monitoring patient\'s vital signs',
      'administering anesthesia',
    ],
    'Cardiologist': [
      'heart failure',
      'heart attack',
      'high blood pressure',
      'irregular heartbeat',
      'arrhythmias',
      'aorta disease',
      'marfan syndrome',
      'congenital heart disease',
      'coronary artery disease',
      'narrowing of the arteries',
      'deep vein thrombosis',
      'pulmonary embolism',
      'heart muscle disease',
      'cardiomyopathy',
      'high cholesterol',
      'stroke',
      'heart rhythm problems',
      'congestive heart failure',
    ],
    'Colon and Rectal Surgeon': [
      'colon cancer',
      'hemorrhoids',
      'inflammatory bowel disease',
      'irritable bowel syndrome',
      'constipation',
      'anal fissures',
      'abscess',
      'colitis',
      'polyps',
      'ulcerative colitis',
      'diverticulitis',
      'rectal bleeding',
      'abdominal discomfort',
    ],
    'Critical Care Medicine Specialist': [
      'life support',
      'invasive monitoring techniques',
      'resuscitation',
      'end of life care',
      'organ dysfunction',
      'organ failure',
    ],
    'Dentist': [
      'tooth diseases',
      'broken tooth',
      'reduce gaps between teeth',
      'braces',
      'tooth implant',
      'tooth decay',
      'misshaped tooth',
      'tooth removal',
      'tooth cavity fillings',
      'gum disease',
      'gingivitis',
      'periodontitis',
      'oral cancer examination',
      'teeth whitening',
    ],
    'Dermatologist': [
      'eczema',
      'skin cancer',
      'acne',
      'psoriasis',
      'skin problems',
      'hair problems',
      'nail problems',
      'disorders of the skin',
      'disorders of the hair',
      'disorders of the nails',
      'scars',
      'acne',
      'skin allergies',
      'adjacent mucous membranes',
      'tumors',
      'inflammatory diseases of the skin',
      'skin infectious diseases',
      'skin biopsies',
      'dermatological surgery',
      'rosacea',
      'ichthyosis',
      'vitiligo',
      'hives',
      'seborrheic dermatitis',
    ],
    'Endocrinologist': [
      'hormonal disorders',
      'hormonal problems',
      'diabetes',
      'thyroid conditions',
      'hormone imbalances',
      'infertility',
      'growth problems',
      'adrenal gland conditions',
      'osteoporosis',
      'thyroid cancer',
      'addison\'s Disease',
      'cushing\'s syndrome',
      'graves Disease',
      'hashimoto\'s thyroiditis',
      'hyperthyroidism',
      'precocious puberty',
      'hypopituitarism',
      'polycystic ovary syndrome (PCOS)',
      'multiple endocrine neoplasia 1 and 2 (MEN I and MEN II)',
    ],
    'Emergency Medicine Specialist': [
      'trauma',
      'sepsis',
      'burn',
      'acute coronary syndrome',
      'poisoning',
      'stroke',
      'acute diseases',
      'injury',
    ],
    'Family Physician': [
      'routine checkups',
      'routine screening tests',
      'minor illness treatment',
      'fever',
      'cold',
      'flu',
      'disease diagnosis',
      'diabetes',
      'hypertension',
      'headache',
    ],
    'Gastroenterologist': [
      'abdominal pain',
      'ulcers',
      'diarrhea',
      'jaundice',
      'inflammatory bowel disease',
      'constipation',
      'digestive organs cancers',
      'colonoscopy',
      'endoscopy',
      'sigmoidoscopy',
      'colon cancer diagnosis',
      'gastroesophageal reflux disease (GERD)',
      'gallstones',
      'celiac disease',
      'crohn\'s disease',
      'ulcerative colitis',
      'irritable bowel syndrome',
      'hemorrhoids',
      'diverticulitis',
      'anal fissure',
    ],
    'Geriatrician': [
      'dementia',
      'delirium',
      'sleep problems',
      'bladder control problems',
      'alzheimer\'s disease',
      'injuries from falling',
      'osteoporosis',
      'weight loss',
    ],
    'Haematologist': [
      'anemia',
      'HIV',
      'blood clots',
      'lymphoma',
      'myeloma',
      'blood cell cancers',
      'blood diseases',
      'sickle cell disease',
      'hemophilia',
      'leukemia',
      'myelofibrosis',
      'essential thrombocythemia',
      'eosinophilia',
      'mastocytosis',
      'histiocytosis',
    ],
    'Hepatologist': [
      'hepatitis a',
      'hepatitis b',
      'hepatitis c',
      'gastrointestinal bleeding',
      'portal hypertension',
      'jaundice',
      'ascites',
      'enzyme defects',
      'biliary tree diseases',
      'hydatid cyst',
      'kala-azar',
      'schistosomiasis',
      'hemochromatosis',
      'pancreatitis',
    ],
    'Hospice and Palliative Medicine Specialist': [
      'pain management',
      'acute sickness care',
    ],
    'Infectious Disease Specialist': [
      'fevers',
      'lyme disease',
      'pneumonia',
      'tuberculosis',
      'HIV',
      'AIDS',
      'herpes',
      'hepatitis b',
      'hepatitis c',
      'cellulitis',
      'influenza',
      'bacterial infections',
      'clostridium difficile',
      'surgical infections',
      'parasite infections',
      'fungi infections',
      'virus infections',
      'blastomycosis',
      'bone and joint infections',
      'urinary tract infections,',
      'heart valve infections',
      'malaria',
      'tropical diseases',
      'measles',
      'mumps',
      'rubella',
      'meningitis',
      'methicillin-resistant staphylococcus aureus (MRSA)',
      'post operative infections',
      'rheumatic fever',
      'tick-borne infections',
    ],
    'Internist': [
      'routine checkups',
      'routine screening tests',
      'minor illness treatment',
      'fever',
      'cold',
      'flu',
      'disease diagnosis',
      'diabetes',
      'hypertension',
      'headache',
    ],
    'Medical Geneticist': [
      'mitochondrial encephalopathy',
      'myoclonic epilepsy with ragged red fibers (MERRF)',
      'leber\'s hereditary optic neuropathy',
      'cry of the cat syndrome',
      'Cri du chat syndrome',
      'klinefelter syndrome',
      'turner syndrome',
      'down syndrome',
      'cystic fibrosis',
      'alpha-thalassemias',
      'beta-thalassemias',
      'thalassemia',
      'tay-sachs disease',
      'sickle cell anemia (sickle cell disease)',
      'marfan syndrome',
      'fragile X syndrome',
      'huntington\'s disease',
      'hemochromatosis',
      'cytogenetic',
      'radiologic',
      'biochemical testing',
    ],
    'Neonatologist': [
      'breathing disorders',
      'infections',
      'birth defects',
    ],
    'Nephrologist': [
      'kidney inflammation',
      'dialysis',
      'kidney diseases',
      'kidney diseases',
      'kidney cancer',
      'kidney transplant',
      'high blood pressure',
      'renal (kidney) failure',
      'diabetes',
      'kidney stones',
      'lupus',
      'hypertension',
    ],
    'Neurologist': [
      'strokes',
      'seizures',
      'brain tumors',
      'spinal tumors',
      'epilepsy',
      'parkinson\'s disease',
      'alzheimer\'s disease',
      'multiple sclerosis',
      'neuropathy',
      'migraine',
      'acute spinal cord injury',
      'amyotrophic lateral sclerosis (ALS)',
      'ataxia',
      'bell\'s palsy',
      'cerebral aneurysm',
      'brain injury',
      'brain diseases',
      'guillain-barré syndrome',
      'headache',
      'head injury',
      'hydrocephalus',
      'lumbar disk disease (herniated disk)',
      'meningitis',
      'neurocutaneous syndromes',
      'cluster headaches',
      'tension headaches',
      'migraine headaches',
      'encephalitis',
      'myasthenia gravis',
      'moyamoya disease',
      'motor stereotypes'
    ],
    'Nuclear Medicine Radiologist': [
      'scintigraphy',
      'cancer',
      'hyperthyroidism',
      'thyroid cancer',
      'lymphomas',
      'tumors',
      'bone cancer',
    ],
    'Obstetrician and Gynecologist': [
      'labor and delivery',
      'pregnancy',
      'pregnancy problems',
      'pregnancy diagnosis',
      'antenatal care',
      'postnatal care',
      'caesareans (C Sections)',
      'menopausal hormone replacement therapy',
      'female infertility',
      'bacterial vaginosis',
      'cervical cancer',
      'cervical dysplasia',
      'menopause',
      'miscarriage',
      'mullerian anomalies',
      'ovarian cancer',
      'ovarian cysts',
      'ovarian remnant syndrome',
      'premature birth',
      'sexually transmitted diseases (STD)',
      'vaginal atrophy',
      'vaginal bleeding',
      'vaginal cancer',
      'vaginal fistula',
      'yeast infection (vaginal)',
    ],
    'Oncologist': [
      'carcinoma',
      'sarcoma',
      'melanoma',
      'lymphoma',
      'leukemia',
      'chemotherapy',
      'cancer',
      'skin cancer',
      'lungs cancer',
      'breasts cancer',
      'pancreas cancer',
      'lung cancer',
      'prostate cancer',
      'colorectal cancer',
      'kidney (renal) cancer',
      'bladder cancer',
      'non-hodgkin\'s lymphoma'
    ],
    'Ophthalmologist': [
      'glaucoma',
      'macular degeneration',
      'diabetic retinopathy',
      'eye dehydration',
      'amblyopia',
      'strabismus',
      'proptosis',
      'uveitis',
      'eye tumors',
      'laser refractive surgery',
      'cataract',
      'strabismus',
      'diabetic retinopathy',
      'cataract surgery',
      'corneal transplantation',
    ],
    'Osteopath': [
      'shoulder pain',
      'elbow pain',
      'arm pain',
      'neck pain',
      'lower back pain',
      'muscles problems',
      'bones problems',
      'joints problems',
    ],
    'Otolaryngologist/ENT Specialist': [
      'nose injury',
      'ear surgery',
      'nose surgery',
      'throat surgery',
      'sinuses surgery',
      'head surgery',
      'neck surgery',
      'ear problems',
      'nose problems',
      'throat problems',
      'sinuses problems',
      'head problems',
      'neck problems',
      'cholesteatoma',
      'dysphagia (difficulty swallowing)',
      'ear infection (otitis media)',
      'gastric reflux',
      'hearing aids',
      'hearing loss',
      'hoarseness',
      'meniere\'s',
      'nosebleeds',
      'sinus problems',
      'sleep apnea',
      'snoring',
      'swimmer\'s ear (otitis externa)',
      'tinnitus (ringing in the ears)',
      'tonsils',
      'adenoid problems',
    ],
    'Pathologist': [
      'clinical laboratory tests',
      'clinical lab tests',
      'tissues examination',
      'cells examination',
      'body fluids examination',
    ],
    'Pediatrician': [
      'child problems',
      'children problems',
      'infant diseases',
      'infant health issues',
      'asthma in children',
      'allergies',
      'croup',
      'chickenpox (varicella)',
      'coughs in children',
      'colds in children',
      'ear infections in children',
      'diarrhoea in children',
      'vomiting in children',
      'fever in children',
      'food allergies in children',
      'measles',
      'mumps',
    ],
    'Physiatrist': [
      'accident recovery',
      'injury recovery',
      'trauma recovery',
      'surgical recovery',
      'pediatric rehabilitation',
    ],
    'Plastic Surgeon': [
      'craniofacial surgery',
      'hand surgery',
      'facial surgery',
      'birth defect surgery',
      'plastic surgery',
      'breast implant surgery',
      'breast removal surgery',
    ],
    'Podiatrist': [
      'foot injury',
      'ankle injury',
      'foot pain',
      'ankle pain',
      'foot problems',
      'ankle problems',
    ],
    'Psychiatrist': [
      'disease control',
      'hazard control',
      'disease prevention',
      'injury prevention',
      'disease causes',
    ],
    'Pulmonologist': [
      'asthma',
      'tuberculosis',
      'lung cancer',
      'pneumonia',
      'emphysema',
      'trouble sleeping caused by breathing difficulty',
      'breathing issues',
      'breathing difficulty',
      'chronic obstructive lung disease (COPD)',
      'interstitial lung disease',
      'occupational lung disease',
      'chronic bronchitis',
      'cystic fibrosis',
      'bronchiectasis',
      'pleural effusion',
    ],
    'Radiologist': [
      'mammograms',
      'ultrasound',
      'x-ray',
      'magnetic resonance imaging (MRI)',
      'computed tomographic scan (CT scan)',
      'positron emission tomography scan (PET scan)',
    ],
    'Rheumatologist': [
      'rheumatoid arthritis',
      'osteoarthritis',
      'gout',
      'lupus',
      'scleroderma',
      'psoriatic arthritis',
      'immune-mediated disorders',
      'tissue illnesses',
      'autoimmune diseases',
      'rheumatic diseases',
      'back pain',
      'bursitis',
      'tendinitis',
      'capsulitis',
      'neck pain',
      'fibromyalgia',
      'osteoporosis (weak bones)',
    ],
    'Surgeon': [
      'tumor surgery',
      'appendice surgery',
      'gallbladders surgery',
      'hernia repair surgery',
      'cancer surgery',
      'hand surgery',
      'vascular surgery',
      'colon and rectal surgery',
      'general surgery',
      'neurological surgery',
      'ophthalmic surgery',
      'oral and maxillofacial surgery',
      'orthopaedic surgery',
      'otolaryngology',
      'thoracic surgery',
      'ear surgery',
      'nose surgery',
      'throat surgery',
      'leg surgery',
      'arm surgery',
      'hand surgery',
    ],
    'Urologist': [
      'urinary tract infections',
      'kidney diseases',
      'kidney stones',
      'leaky bladder',
      'urinary tract problems',
      'bladder problems',
      'prostate cancer',
      'male infertility',
      'renal transplant',
      'prostate cancer',
      'bladder cancer',
      'bladder prolapse',
      'hematuria (blood in the urine)',
      'erectile dysfunction (ED)',
      'interstitial cystitis (painful bladder syndrome)',
      'overactive bladder',
      'prostatitis (swelling of the prostate gland)',
    ],
  };
}